name: Data fetch - DMV - to DB flow (Python)

on:
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you need
          
      # Install Python packages
      - name: Install Python packages
        run: |
          pip install pandas numpy matplotlib seaborn mysql-connector-python sqlalchemy requests

      # Run each Python script with error handling
      - name: Run dmv_tvv_pct.py
        run: python dmv_tvv_pct.py
        continue-on-error: true

      - name: Run sql_refresh.py
        run: python refresh_aws_sql.py
        continue-on-error: true    

      - name: Run dmv_osc_mom_rat.py
        run: python dmv_osc_mom_rat.py
        continue-on-error: true
        
      - name: Run sql_refresh.py (2nd time)
        run: python refresh_aws_sql.py
        continue-on-error: true    

      - name: Run dmv_met.py
        run: python dmv_met.py
        continue-on-error: true
        
      - name: Run sql_refresh.py (3rd time)
        run: python refresh_aws_sql.py
        continue-on-error: true    

      - name: Run dmv_core.py
        run: python dmv_core.py
        continue-on-error: true

      - name: Run cc_info.py
        run: python cc_info.py
        continue-on-error: true
