name: Data fetch - DMV - to DB flow (Python)

on:
  schedule:
    - cron: "30 0 * * *"  # Daily at midnight UTC
  workflow_dispatch: {}


jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you need
          
      # Install Python packages
      - name: Install Python packages
        run: |
          pip install pandas numpy matplotlib seaborn mysql-connector-python sqlalchemy requests
          
      # Run the Python script
      - name: Run dmv_tvv_pct.py
        run: python dmv_tvv_pct.py

      # Run the Python refresh sql con #
      - name: Run sql_refresh.py
        run: python refresh_aws_sql.py    

      # Run the Python script
      - name: Run dmv_osc_mom_rat.py
        run: python dmv_osc_mom_rat.py
        
      # Run the Python refresh sql con #
      - name: Run sql_refresh.py
        run: python refresh_aws_sql.py    

      # Run the Python script
      - name: Run dmv_met.py
        run: python dmv_met.py
        
      # Run the Python refresh sql con #
      - name: Run sql_refresh.py
        run: python refresh_aws_sql.py    
  
      # Run the Python script
      - name: Run dmv_core.py
        run: python dmv_core.py

      # Run the Python script
      - name: Run cc_info.py
        run: python cc_info.py
