name: LISTINGS

on:
  schedule:
# Run every day at 5 AM UTC
    - cron: '05 0 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  fetch-crypto-data:
    runs-on: ubuntu-latest
    environment: testsecrets
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run crypto data fetcher
      env:
        # Database configuration
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_NAME_BT: ${{ secrets.DB_NAME_BT }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_URL: ${{ secrets.DB_URL }}
        
        # API Keys
        CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        
        # Telegram configuration
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python gcp_postgres_sandbox/data_ingestion/cmc_listings.py
    
    - name: Log completion
      run: echo "Crypto data fetch completed at $(date)"
