name: pytest

on:
  #schedule:
  # - cron: "30 19 * * *"  # Daily at 00:30 UTC
  workflow_dispatch: {}

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you need

      # Install Python packages
      - name: Install Python packages
        run: |
          pip install pandas numpy matplotlib seaborn mysql-connector-python sqlalchemy requests psycopg2-binary
          

      # Run each Python script with error handling
      - name: Run db_test.py
        run: python gcp_postgres_sandbox/prod_qa_ap_ai.py
        continue-on-error: false
        
